
RESTORE filelistonly from disk ='c:\DbBackup\MES.BAK'

RESTORE DATABASE MES_LOCAL
    FROM DISK='c:\DbBackup\MES.BAK'
    WITH MOVE 'MESPERPAPER_DEV'       TO 'c:\DbBackup\MES_LOCAL.MDF',
	MOVE 'MESPERPAPER_DEV_LARGE_FILE' TO 'c:\DbBackup\MES_LOCAL_1.NDF',
	MOVE 'MESPERPAPER_DEV_LOGS_FILE'  TO 'c:\DbBackup\MES_LOCAL_2.NDF',
    MOVE 'MESPERPAPER_DEV_log'        TO 'c:\DbBackup\MES_LOCAL_log.ldf'
,STATS=10, RECOVERY

SP_HELPDB MES_LOCAL